import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useRef, useState } from "react";
import cv from "@techstark/opencv-js";
import {
  detectHaarFace,
  loadHaarFaceModels,
} from "../components/haarFaceDetection";

export default function Home() {
  const [modelLoaded, setModelLoaded] = React.useState(false);
  ////////////////////////////////////////////////////////////////
  React.useEffect(() => {
    loadHaarFaceModels().then(() => {
      setModelLoaded(true);
    });
  }, []);
  //////////////////////////////////////////////////////////////
  const canvas1 = useRef();
  const img1 = useRef();
  //////////////////////////////////////////////////////////////
  function handleFileChange(e) {
    const files = e.target.files;
    if (!files || files.length === 0) {
      return;
    }
    const file = files[0];
    var fr = new FileReader();
    fr.readAsDataURL(file);
    var img = img1.current;
    fr.onload = (evt) => {
      if (evt.target.readyState === FileReader.DONE) {
        img.src = evt.target.result;
      }
    };
  }
  //////////////////////////////////////////////////////////
  function handleImageLoad() {
    var img = img1.current;
    img2canvas(img, canvas1.current);
    img.className = "";
  }
  /////////////////////////////////////////////////
  function img2canvas(img, canvas) {
    var ctx = canvas.getContext("2d");
    var ratioImage = img.naturalWidth / img.naturalHeight;
    var widthAdj = 400; //canvas.width
    var heightAdj = Math.ceil(widthAdj / ratioImage);

    canvas.width = widthAdj; //(img.width/2)
    canvas.height = heightAdj; // (img.height/2)

    ctx.width = widthAdj + "px"; //(img.width/2) + 'px'
    ctx.height = heightAdj + "px"; //(img.height/2) + 'px'
    ctx.drawImage(img, 0, 0, widthAdj, heightAdj);
  }
  /////////////////////////////////////////////////////////////////////
  async function testOpenCv() {
    if (!modelLoaded) return;
    var img = img1.current;
    var mat = cv.imread(img);
    const haarFaces = detectHaarFace(mat);
    cv.imshow(canvas1.current, haarFaces);
    // await cv.imshow(faceImgRef.current, img);
    // await cv.cvtColor(mat, mat, cv.COLOR_RGBA2GRAY);
    // await cv.bitwise_not(mat, mat);
    // await cv.imshow(canvas1.current, mat);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Test</h1>
        <div>
          <label className="btn">file: </label>
          <input id="file" type="file" onChange={handleFileChange} />
          <br />
          <button type="button" onClick={testOpenCv}>
            Test OpenCv!
          </button>
          <br />
          <br />
        </div>
        <div>
          <img
            src=""
            alt="testimg"
            ref={img1}
            onLoad={handleImageLoad}
            style={{ display: "none" }}
          />
          <br />
        </div>
        <div>
          <canvas ref={canvas1}></canvas>
        </div>
      </main>
    </div>
  );
}

///////////////////////////////////////////////////////////////////////////////////////////////

// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import { useSmartcrop, SmartcropStatus } from "use-smartcrop";
// import React, { useEffect } from "react";

// export default function Home() {
//   //////////////////////////////////////////////////////////////////

//   // const src = "/test.jpg";
//   // // Width and height are required.
//   // const [cropped, error] = useSmartcrop(
//   //   { src },
//   //   { width: 100, height: 150, minScale: 1.0 }
//   // );
//   // if (error) {
//   //   console.error(error);
//   // }

//   ////////////////////////////////////////////////////////////////////

//   return (
//     <div style={{ diplay: "grid", margin: "auto" }}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       {/* /////////////////////////////////////////////////////// */}
//       {/* <div>{cropped && <img src={cropped} />}</div> */}
//       {/* /////////////////////////////////////////////////////// */}
//     </div>
//   );
// }

////////////////////////////////////////////////////////////////////////////////////////////////////////////
